### ISSUE TITLE
"fixtures" folder should not be required

### ISSUE THREAD

**Issue by lucifurtun** [colibris-framework/colibris#38]
Right now `__packagename__/tests/fixtures` needs to be present if you want to successfully run the tests. If not there, this error is thrown:

`ImportError: Error importing plugin "__packagename__.tests.fixtures": No module named '__packagename__.tests.fixtures'`.

"fixtures" folder should not be required.

**Comment by ccrisan** [comment]
Fixed via ecb6817894785e171fd10e4330ed292c9cce708c.
